# Generated by Django 4.2.18 on 2025-12-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Date')),
                ('check_in_time', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('status', models.CharField(choices=[('present', 'Présent'), ('late', 'Retard'), ('absent', 'Absent')], default='present', max_length=20, verbose_name='Statut')),
                ('confidence_score', models.FloatField(blank=True, help_text='Score de reconnaissance faciale (0-1)', null=True, verbose_name='Score de confiance')),
                ('capture_image', models.ImageField(blank=True, null=True, upload_to='photos/captures/', verbose_name='Image capturée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.course', verbose_name='Cours')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Étudiant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-attendance_date', '-check_in_time'],
                'indexes': [models.Index(fields=['student', 'attendance_date'], name='attendance__student_41cda6_idx'), models.Index(fields=['course', 'attendance_date'], name='attendance__course__839c60_idx')],
                'unique_together': {('student', 'course', 'attendance_date')},
            },
        ),
    ]
