# Generated by Django 4.2.18 on 2025-12-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True, verbose_name='Code du cours')),
                ('course_name', models.CharField(max_length=255, verbose_name='Nom du cours')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salle')),
                ('schedule_day', models.CharField(blank=True, choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi')], max_length=20, null=True, verbose_name='Jour')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('duration', models.IntegerField(blank=True, help_text='Durée du cours en minutes', null=True, verbose_name='Durée (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['course_code'],
            },
        ),
    ]
