# Generated by Django 4.2.18 on 2025-12-06 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir uniquement des lettres majuscules et des chiffres', regex='^[A-Z0-9]+$')], verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programme')),
                ('year_level', models.IntegerField(blank=True, choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4'), (5, 'Niveau 5')], null=True, verbose_name='Niveau')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/students/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['student_number'], name='students_st_student_0be38d_idx'), models.Index(fields=['last_name', 'first_name'], name='students_st_last_na_3e473b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField(verbose_name='Encodage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='students.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Encodage Facial',
                'verbose_name_plural': 'Encodages Faciaux',
            },
        ),
    ]
